#!/usr/bin/env bash

# Checks for number of paramters
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_kEY""$FILE_PATH""$USERNAME@$SERVER_IP":~/
exit 0