#!/usr/bin/env bash
# A bash script that Install nginx web server
# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create nginx html directory
sudo mkdir -p /etc/nginx/html

# Create an empty index.html file in the nginx directory
sudo touch /etc/nginx/html/index.html

# Ensure nginx is listening on port 80
sudo printf "%s\n" "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx service to apply new changes
sudo service nginx restart