#!/usr/bin/env bash
# Installs Nginx with the following configurations:

#  updates the package lists
apt-get update
# install the Nginx web server.
apt-get install -y nginx

# Creates the /etc/nginx/html directory for nginx
mkdir /etc/nginx/html
#  creates an empty index.html file inside the nginx htm directory.
touch /etc/nginx/html/index.html
#  sets the content of the index.html file to "Hello World!"
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restarts the Nginx service to commit changes.
service nginx restart