#!/bin/env bash
# script that Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
# Run the script as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Please use sudo." 
    exit 1
fi

# Create or overwrite index.html with custom 404 page content
echo "Ceci n'est pas une page." > /var/www/html/404.html

# Configure Nginx to listen on port 80 and serve files from /var/www/html
printf %s "server {
        listen      80;
        listen      [::]:80 default_server;
        root        /var/www/html;
        index       index.html index.htm;
        
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
}
" > /etc/nginx/sites-available/default

# Test the Nginx configuration and reload the server
nginx -t && service nginx reload

echo "Custom 404 page configured successfully."