#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

# Install HAproxy
sudo apt-get install -y haproxy

# Enable HAproxy management via the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAproxy
configure_haproxy() {
    cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 247068-web-01 100.27.13.53:80 check
    server 247068-web-02 100.25.37.138:80 check
EOT
}

configure_haproxy

# Restart HAproxy service
sudo service haproxy restart
