#!/usr/bin/env bash
# Generate MySQL dump and create a compressed archive

# Get current date for the archive name
current_date=$(date +"%d-%m-%Y")
sudo mysqldump -u root -p --all-databases > backup.sql
tar -czvf "$current_date.tar.gz" backup.sql
rm backup.sql
