#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration file
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart