#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ./hosts_cpy
echo -e "COPY OF THE HOSTS-F HAS BEEN CREATED IN YOUR CURRENT DIR!!\n"
echo "127.0.0.2	localhost" > ./hosts_cpy
echo "8.8.8.8	facebook.com" >> ./hosts_cpy
cp -f ./hosts_cpy /etc/hosts
