#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts .
echo -e "\n\e[31mA COPY OF THE HOSTS FILE HAS BEEN CREATED IN YOUR CURRENT DIR!!\n\e[0m"
echo "127.0.0.2	localhost" > /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
