#!/usr/bin/env bash
#a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ips=$(ifconfig | grep "inet " | awk '{print $2}' | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}$")

for ip in $ips; do
	echo $ip
done
