#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the default port to 8080 in the Nginx default site configuration
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Change the default port to 8080 in any other Nginx site configurations if necessary
# sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/...

# Make sure the Nginx configuration has the correct permissions
chmod 644 /etc/nginx/nginx.conf

# Restart Nginx to apply changes
service nginx restart