#!/usr/bin/bash
# script that uses ssh to connect to your
# server using the private key ~/.ssh/school with the user ubuntu.

server_address="34.224.94.98"
private_key="/root/.ssh/school"
username="ubuntu"

ssh -i "$private_key" "$username"@"$server_address"
